config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#top'
  post 'rooms/new',to: 'room#new'
  post 'resevation/confirm'
  get 'users/account',to: 'users#show'
  get 'users/profile'
  post 'users/profile'
  patch 'users/update'
  post 'users/update'
  get 'rooms/posts'
  get 'rooms/search'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :rooms
  resources :reservations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    belongs_to :room

    end

    
    

app/models/room.rb
class Room < ApplicationRecord

    has_one_attached :image  
    validates :name, presence: true
    validates :price, presence: true
    validates :address, presence: true
    validates :image, presence: true
    
    belongs_to :user
    has_many :reservations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
 has_one_attached :image

 has_many :rooms
 has_many :reservations

 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def top
        @q = Room.ransack(params[:q])
        @results = @q.result(distinct: true)
    end
    
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @q = Room.ransack(params[:q])
    @results = @q.result(distinct: true)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
 
 def index
    @reservations=Reservation.where(user_id: current_user.id)
 end

 def new
    @room=Room.find(params[:reservation][:room_id])
    @reservation=Reservation.new(reservation_params)

    if @reservation.start == nil||@reservation.end == nil||@reservation.number == nil
      redirect_to room_path(@reservation.room_id) 
      flash[:notice]="必須項目を入力してください" and return
    else 
      @price=@room.price*@reservation.number*(@reservation.end-@reservation.start).to_i
      @days=(@reservation.end-@reservation.start).to_i
    end

    if @days < 1
      redirect_to room_path(@reservation.room_id)
      flash[:notice]="終了日は開始日以降にしてください"   
    elsif @reservation.start < Date.today
      redirect_to room_path(@reservation.room_id)
      flash[:notice]="過去の日付は入力しないでください"   
    elsif @reservation.number <= 0
      redirect_to room_path(@reservation.room_id)
      flash[:notice]="人数は１人以上にしてください" 
    end
 end

 def create
    @reservation=Reservation.new(params.require(:reservation).permit(:start,:end,:number,:user_id,:room_id))
    @reservation.save
    redirect_to("/reservations/#{@reservation.id}")
 end

 def show
    @reservation=Reservation.find(params[:id])
    @room=Room.find_by(id: @reservation.room_id)
    @price=@room.price*(@reservation.end-@reservation.start).to_i
 end
    

 def edit
 end

 def update
 end

 def destroy
 end

 def reservation_params
    params.require(:reservation).permit(:start, :end, :number, :user_id, :room_id)
 end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def index
    @users=User.all
  end
  
  def new
    @room=Room.new
  end

  def create
    @room = Room.new(params.require(:room).permit(:name, :introduce, :price, :address, :image, :user_id))
    if @room.save
      redirect_to("/rooms/#{@room.id}")
    else
      render("rooms/new")
   end
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def posts
    @rooms=Room.where(user_id: current_user.id)
  end

  def search
    @q = Room.ransack(params[:q])
    @results = @q.result(distinct: true)
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user=User.new
  end

  def show
    @user=User.find_by(id: current_user.id)
  end

  def update
    @user=current_user
    if @user.update(user_params)
       flash[:notice]="更新しました"
       redirect_to users_profile_path
    end
  end

  def profile
    @user=current_user
  end

  private
  def user_params
    params.require(:user).permit(:image,:name,:introduce)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="top-main">
 <div class="container">
  <div class="form-frame">
   <div class="form-area">
    <p class="form-area-title">Potepan Shareで<br>まだ体験したことのない旅をしよう</p>
     <%= search_form_for @q, url: rooms_search_path do |f| %>
      <%= f.label :address_cont, 'エリア' ,class:'search-word'%><br>
      <%= f.search_field :address_cont %><br>
      <%= f.label :name_or_address_or_introduce_cont, 'キーワード',class:'search-word'%><br>
      <%= f.search_field :name_or_address_or_introduce_cont %>
      <br>
      <div class="search-submit">
       <%= f.submit '検索' ,class:'seach-submit'%>
      </div>
     <% end %>
    
   </div>
  </div>
 </div>
</div>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoteShare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header class="header">
    <div class ="header-container">
     <div class="header-left-nav">
      <a href="/">
       <img alt="サイトのロゴ" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png">
      </a>
      </div>
     <div class="header-right-nav">
      <nav>
       <% if user_signed_in? %>
        <%= "#{current_user.name}さん"  %>
        <details>
         <summary>メニュー</summary>
          <ul class="header-nav-menu">
           <li><a href="/rooms/new">ルーム登録</a></li>
           <li><a href="/reservations">予約済みルーム一覧</a></li>
           <li><a href="/rooms/posts">登録済みルーム一覧</a></li>
           <li><a href="/users/account">設定</a></li>
           <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          </ul>
        </details>
       <% else %>
        <button class="before-login"><%= link_to '新規登録', new_user_registration_path %></button>
        <button class="before-login"><%= link_to 'ログイン', new_user_session_path %></button>
       <% end %>
      </nav>
     </div>
    </div>  
   </header>
    <%if flash.notice%>
     <p class="notice"><%= notice %></p>
    <%end%>
    <%if flash.alert%>
     <p class="alert"><%= alert %></p>
    <%end%>

    <main>
     <%= yield %>
    </main>

    <footer class="footer">
     <p>©️ 2020 POTEPAN.INC</p>
    </footer>
  </body>
</html>

app/views/reservations/index.html.erb
<div class="reservation-room-list">
 <h2>予約済みルーム一覧</h2>
 
 <table class="reservation-room-detail">
  <tr>
   <th>ルーム画像</th>
   <th>ルーム名</th>
   <th>ルーム紹介</th>
   <th>合計料金</th>
   <th>開始日</th>
   <th>終了日</th>
   <th>予約確定日時</th>
  </tr>
  
  <% @reservations.each do |reservation| %>
  <tr>
   <td><%= image_tag reservation.room.image %></td>
   <td><%= reservation.room.name %></td>
   <td><%= reservation.room.introduce %></td>
   <td><%= reservation.room.price*reservation.number*(reservation.end-reservation.start).to_i %>
   <td><%= reservation.start %></td>
   <td><%= reservation.end %></td>
   <td><%= l reservation.created_at %></td>
  </tr>
  <% end %>
   
  </table>
</div>

app/views/reservations/new.html.erb
<div class="reservation-new">
 <table class="reservation-new-detail">
  <tr>
   <th colspan="2" class="title">予約内容確認</th>
  </tr>
  <tr>
   <th colspan="2" class="price">¥<%= @room.price %>/日</th>
  </tr>
  <tr>
   <td width="40%">開始日</td>
   <td width="60%"><%= @reservation.start %></td>
  </tr>
  <tr>
   <td>終了日</td>
   <td><%= @reservation.end %></td>
  </tr>
  <tr>
   <td>泊数</td>
   <td><%= @days %>泊</td>
  </tr>
  <tr>
   <td>人数</td>
   <td><%= @reservation.number %>名</td>
  </tr>
  <tr>
   <td>合計金額</td>
   <td><%= @price %>円</td>
  </tr>
  <tr>
   <td colspan="2" class="notice">上記内容でよろしければ「予約を確定」を押してください</td>
  </tr>
  </table>

   <%= form_with model: @reservation do |f|%>
    <%= f.hidden_field :room_id, value: @room.id%>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :start %>
    <%= f.hidden_field :end %>
    <%= f.hidden_field :number %>
    <div class="reservation-submit">
     <%=f.submit "予約を確定" %>
    </div>
    
   <% end %>
   
   <div class="reservation-button">
    <%= link_to ("/rooms/#{@room.id}")do %>
     <button class="reservation-back">ルーム詳細に戻る</button>
    <% end %>
   </div>
   
  
</div>

app/views/reservations/show.html.erb
<div class="reservation-complete">
 <div class="complete-title">
  <h1>予約が完了しました</h1>
 </div>
 
 <table class="complete-detail">
  <tr>
   <td>予約した部屋</td>
   <td><%= @room.name %></td>
  </tr>
  <tr>
   <td>開始日</td>
   <td><%= @reservation.start %></td>
  </tr>
  <tr>
   <td>終了日</td>
   <td><%= @reservation.end %></td> 
  </tr>
  <tr>
   <td>価格</td>
   <td><%= @price %>
  </tr>
 </table>

app/views/rooms/new.html.erb
<div class="room-register">
 <div class="room-register-box">
  <h2>ルーム情報登録</h2>

  <%= render "shared/error", obj: @room %>
 
  <%= form_with model: @room do |f| %>
   <table class="update-content">
    <tr>
     <th><%= f.label :name,"ルーム名" %></th>
     <td><%= f.text_field :name %></td>
    </tr>
    
    <tr>
     <th><%= f.label :introduce,"ルーム紹介" %></th>
     <td><%= f.text_area :introduce %></td>
    </tr>
   
    <tr>
     <th><%= f.label :price,"料金" %></th>
     <td><%= f.number_field :price %></td>
    </tr>
   
    <tr>
     <th><%= f.label :address,"住所" %></th>
     <td><%= f.text_field :address %></td>
    </tr>
   
    <tr>
     <th><%= f.label :room_image,"ルーム画像" %></th>
     <td><%= f.file_field :image %></td>
    </tr>
   </table>

   <div class ="submit-form">
    <h3><%= f.submit "登録" %></h3>
   </div>
   <%= f.hidden_field :user_id, value: current_user.id %>
  <% end %>
 </div>
 </div>

app/views/rooms/posts.html.erb
<div class="reservation-room-list">
 <h2>登録済みルーム一覧</h2>
 
 <table class="reservation-room-detail">
  <tr>
   <th>ルーム画像</th>
   <th>ルーム名</th>
   <th>ルーム紹介</th>
   <th>料金</th>
   <th>作成日</th>
  </tr>
  
  <% @rooms.each do |room| %>
  <tr>
   <td><%= image_tag room.image %></td>
   <td><%= link_to room.name, controller:'rooms',action:'show',id:room.id %></td>
   <td><%= room.introduce %></td>
   <td><%= room.price %></td>
   <td><%= l room.created_at %></td>
  </tr>
  <% end %>
   
  </table>
</div>

app/views/rooms/search.html.erb
<div class="room-search-result">
 <h2>検索結果：<%= @results.count%>件</h2>
 <div class="room-search-list">
 <% @results.each do |room| %>
  <div class="room-search-detail">
  <%= link_to room_path(room.id) do %>
   <div class="room-search-image">
    <%= image_tag room.image %>
   </div>
   <div class="room-search-content">
    <p class="search-room-name"><%= room.name %></p>
    <p class="search-room-address"><%= room.address %></p>
    <p class="search-room-price">¥<%= room.price %></p>
   </div>
   <% end %>
   </div>
  


 <% end %>

app/views/rooms/show.html.erb
<div class="container-room">
 <div class="room-show-about">
  <div class="room-show-about-image">
   <%= image_tag @room.image %>
  </div>
  <div class="room-show-detail">
   <div class="room-show-detail-icon">
    <a href="/">
     <img class="host-icon" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon.jpg">
    </a>
   </div>
   <div class="room-show-profile">
    <p class="room-show-name"><%= @room.name %></p>
    <p class="room-show-address"><%= @room.address %></p>
   </div>
  </div>
  <p class="room-show-introduce">
   <%= @room.introduce %>
  </p>
 </div>

 <div class="room-show-nav">
  <h5 class="price-icon">
   ¥<%= @room.price %>/日
  </h5>
  <div class="room-show-date-select">
   <%= form_with model: @reservation, method: :get, url: new_reservation_path do |f| %>
    <% if user_signed_in? %>
     <%= f.hidden_field :room_id, value: @room.id %>
     <%= f.hidden_field :user_id, value: current_user.id %>
    <% end %>

   <%= f.label :start,"開始日" %><br>
   <%= f.date_field :start %><br>
   <%= f.label :end,"終了日" %><br>
   <%= f.date_field :end %><br>
   <%= f.label :number,"人数" %><br>
   <%= f.number_field :number %><br>

  </div>
  <div class="room-show-date-submit">
   <% if user_signed_in? %>
    <%= f.submit"予約する"%>
   <% else %>
    <button class="room-show-login"><%= link_to "ログイン","new_user_session_path"%></button>
   <% end %>

   <% end %>
  </div>
 </div>
</div> 
 

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
 <% obj.errors.full_messages.each do|message| %>
  <ul>
   <li><%= message %></li>
  </ul>
 <% end %>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="user-listings">
 <div class="user-listings-channel">
  <ul>
   <li><%= link_to("アカウント","/users/account") %></li>
   <li><%= link_to("プロフィール","/users/profile")%></li>
  </ul>
 </div>
</div>
 

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/profile.html.erb
<div class="user-profile-container">
 <div class="user-account-sidebar">
  <%= render 'shared/sidebar'%>
 </div>
 
 <div class="user-profile-main">
  <table class="user-profile-detail">
   <tr>  
   <td colspan="2"><h2>プロフィール</h2></td>
   </tr>

   <tr>
    <td colspan="2">
    <% if @user.image.present? %>
     <%= image_tag @user.image %>
    <% else %>
     <%= image_tag ('https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon.jpg')%>
    <% end %></td>
   </tr>

   <%= form_with model: @user do |f| %>
   <tr>
    <td><%= f.label :image,"アイコン画像"%></td>
    <td><%= f.file_field :image,class:'user-profile-icon'%></td>
   </tr>
   <tr>
    <td><%= f.label :name,"名前" %></td>
    <td><%= f.text_field :name,value:@user.name %></td>
   </tr>
   <tr>
    <td><%= f.label :introduce,"自己紹介" %></td>
    <td><%= f.text_area :introduce, value:@user.introduce %></td>
   </tr>

  <tr>
   <td class="user-profile-button"><%= f.submit"更新" %></td>
  </tr>
 </table>
 <% end %>
  

</div>

app/views/users/show.html.erb
<div class="user-account-container">
  <div class="user-account-sidebar">
   <%= render 'shared/sidebar'%>
  </div>

  <div class="user-account-main">
   <table class="user-account-detail">
    <tr>
     <td colspan="2" class="title">アカウント</td>
    </tr>
    <tr>
     <td width="30%">メールアドレス</td>
     <td width="70%"><%= @user.email %></td>
    </tr>
    <tr>
     <td>パスワード</td>
     <td>非表示</td>
    </tr>
   
   <tr>
    <td class="user-edit-buttons"><%= link_to("/users/edit") do %>
     <button class="user-edit-button">編集</button>
    <% end %>
    </td>
   </tr>
   

   </table>

  
 </div>
</div>